### ISSUE TITLE
addslashes bug on Text and Textarea fields

### ISSUE THREAD

**Issue by geogamba** [RadoslavGeorgiev/ultimate-fields#3]
There is a bug when saving content that contains apostrophy or backslash. Everytime the container is saved, it adds a backslash, thus if you save it multiple times, the backslash just keeps on adding up.

before saving
```
Hello World's
```
after first save
```
Hello World\'s
```
after second save and so on...
```
Hello World\\\'s
```
after third save and so on...
```
Hello World\\\\\'s
```

I have narrowed it down the issue to 2 classes

```
wp-content/ultimate-fields/core/classes/Field/Text.php
wp-content/ultimate-fields/core/classes/Field/TextArea.php
```

```
protected function sanitize_value( $value ) {
    // WordPress likes to strip slashes, so we are escaping them here
    return addslashes( $value );
}
```

By removing the addslashes() function it world display correctly, however, I am unsure if this would affect anything else in the plugin.

**Comment by RadoslavGeorgiev** [comment]
Hi @geogamba,

I tried:
- A Text and a Textarea field
- As a top-level field (w/o serialization) and within a repeater (to force serialization)
- On an options page and on a post type

No combination of these scenarios caused any additional backslashes in the saved values for me. I've had similar issues with a beta of version 3, but the exact snippet that you have found fixed them.

Could you please describe the particular situation:
- Are you using PHP or the administration UI to create the fields?
- If using the UI, could you maybe include an export of the fields?
- If using PHP, could you please include a snippet, which indicates where the container is shown and how the fields are define?

**Comment by geogamba** [comment]
@RadoslavGeorgiev 

I have installed the plugin v3.0.2 on a fresh Wordpress installation just to check, but the issue still persists

I am only using the UI to create the fields.  

Here is the exported fields [ultimate-fields-export-json-2018-05-18-07-40.json.txt](https://github.com/RadoslavGeorgiev/ultimate-fields/files/2015940/ultimate-fields-export-json-2018-05-18-07-40.json.txt)

**Comment by RadoslavGeorgiev** [comment]
Hi @geogamba,

The issue should be fixed by https://github.com/RadoslavGeorgiev/ultimate-fields/commit/e42aed91a07e7502b3efce6b9500a1d45bb4dfac

Until now I hadn't realized that post meta is using `stripslashes_deep` and is actually causing a lot of issues that way :)

Now I am intentionally doubling the slashes before calling `update_post_meta` in order to let it strip just one set, instead of all of them.

Please check out the latest GitHub version and close the issue if everything is fine on your side.

**Comment by geogamba** [comment]
I have checked v3.0.3 and the issue is now solved.

An amazing plugin with amazing support. Thank you @RadoslavGeorgiev
